# Use the official Node.js image as the base image
FROM node:latest

# Set the working directory inside the container
WORKDIR /app

# Install development dependencies
COPY /frontend .
RUN ls
RUN npm install

# Expose the port used by the development server
EXPOSE 8080

# Start the development server
CMD ["npm", "run", "serve"]