version: '3.5'

services:
  app:
    container_name: app
    ports:
      - "8000:8000"
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./app:/usr/src/app
    networks:
      - voz_app_network
      - voz_redis_network
    command: [ "/usr/src/docker/app.sh" ]
    restart: always

  mongodb:
    container_name: mongodb
    image: mongo:latest
    restart: always
    env_file:
      - .env
    volumes:
      - mongodb_data:/data/db
    networks:
      - voz_app_network
    ports:
      - "27017:27017"
  redis:
    container_name: redis
    restart: always
    image: redis:7.0.8
    networks:
      - voz_redis_network
  celery-worker:
    container_name: celery-worker
    build:
      context: .
      dockerfile: Dockerfile  # Use your existing Dockerfile-dev or create a new one
    volumes:
      - ./app:/usr/src/app
    env_file:
      - .env
    networks:
      - voz_app_network
      - voz_redis_network
    command: [ "/usr/src/docker/celery-worker.sh" ]  # Command to start Celery worker
    restart: always
  celery-beat:
    container_name: celery-beat
    depends_on:
      - celery-worker
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./app:/usr/src/app
    env_file:
      - .env
    networks:
      - voz_app_network
      - voz_redis_network
    command: [ "/usr/src/docker/celery-beat.sh" ]
    restart: always
  frontend:
    container_name: frontend
    build:
      context: .
      dockerfile: frontend/Dockerfile-dev
    env_file:
      - frontend/src/.env
    ports:
      - "50000:80"
    volumes:
      - ./frontend:/app
    restart: always
  meilisearch:
    image: getmeili/meilisearch:latest
    env_file:
      - .env
    networks:
      - voz_app_network
    ports:
      - "7700:7700"
    volumes:
      - ./meilisearch_data:/data.ms
    environment:
      - MEILI_DB_PATH=${MEILI_DB_PATH:-/data.ms}
      - MEILI_MASTER_KEY=${MEILI_MASTER_KEY:-masterKey}
      - MEILI_NO_ANALYTICS=${MEILI_NO_ANALYTICS:-true}
      - MEILI_ENV=${MEILI_ENV:-development}
    restart: always
  flower:
    container_name: flower
    image: mher/flower:latest
    command: [ "celery", "flower" ]
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - FLOWER_PORT=5555
    ports:
      - "5555:5555"
    networks:
      - voz_app_network
      - voz_redis_network
    depends_on:
      - celery-worker
    restart: always


networks:
  voz_app_network:
  voz_redis_network:

volumes:
  mongodb_data:
  meilisearch_data:

