version: '3.5'

services:
  flower:
    container_name: flower
    image: mher/flower:latest  # Use the latest Flower image
    command: [ "celery", "flower" ]
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - FLOWER_PORT=5555
    ports:
      - "5555:5555"  # Map Flower web interface port
    networks:
      - app_network
      - redis_network
    depends_on:
      - celery-worker  # Flower depends on the Celery worker
    restart: always