version: '3.5'

services:
  app:
    container_name: app
    ports:
      - "50001:80"
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./app:/usr/src/app
    networks:
      - voz_app_network
      - voz_redis_network
    command: [ "sh", "-c", "uvicorn main:app --host 0.0.0.0 --port 80 --reload" ]
    restart: always
  frontend:
    container_name: frontend
    command: ["sh", "-c", "npm run build && npx http-server dist --port 80"]
    env_file:
      - frontend/src/.env
    build:
      context: .
      dockerfile: frontend/Dockerfile
    ports:
      - "50000:80"
    volumes:
      - ./frontend:/app
    restart: always
  mongodb:
    container_name: mongodb
    image: mongo:latest
    restart: always
    env_file:
      - .env
    volumes:
      - voz_mongodb_data:/data/db
    networks:
      - voz_app_network
    ports:
      - "50002:27017"
  redis:
    container_name: redis
    restart: always
    image: redis:7.0.8
    networks:
      - voz_redis_network
  celery-worker:
    container_name: celery-worker
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./app:/usr/src/app
    env_file:
      - .env
    networks:
      - voz_app_network
      - voz_redis_network
    command: [ "sh", "-c", "celery -A celery_config:app worker --loglevel=info" ]
    restart: always
  celery-beat:
    container_name: celery-beat
    depends_on:
      - celery-worker
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./app:/usr/src/app
    env_file:
      - .env
    networks:
      - voz_app_network
      - voz_redis_network
    command: [ "sh", "-c", "celery -A celery_config:app beat --loglevel=debug" ]
    restart: always
  meilisearch:
    image: getmeili/meilisearch:latest
    env_file:
      - .env
    networks:
      - voz_app_network
    ports:
      - "50003:7700"
    volumes:
      - voz_meilisearch_data:/data.ms
    environment:
      - MEILI_DB_PATH=${MEILI_DB_PATH:-/data.ms}
      - MEILI_MASTER_KEY=${MEILI_MASTER_KEY:-masterKey}
      - MEILI_NO_ANALYTICS=${MEILI_NO_ANALYTICS:-true}
      - MEILI_ENV=${MEILI_ENV:-development}
    restart: always


networks:
  voz_app_network:
  voz_redis_network:

volumes:
  voz_mongodb_data:
  voz_meilisearch_data:

