import os

MONGO_USER = os.getenv('MONGO_INITDB_ROOT_USERNAME')
MONGO_PASS = os.getenv('MONGO_INITDB_ROOT_PASSWORD')
MEILI_MASTER_KEY = os.getenv('MEILI_MASTER_KEY')
MEILISEARCH_URL = os.getenv('MEILISEARCH_URL')
MONGO_PORT = 27017
MONGO_HOST = 'mongodb'
MONGO_DB = 'app'
